### ISSUE TITLE
Process queue results sequentially

### ISSUE THREAD

**Issue by IlyaSemenov** [doo-gl/concurrent-promise-queue#2]
Currently, the proposed way to process results is to gather a single array with `Promise.all` and iterate over it:

```ts
return Promise.all([
  queue.addPromise(() => callApi('/book/1')),
  queue.addPromise(() => callApi('/book/2')),
  queue.addPromise(() => callApi('/book/3')),
  queue.addPromise(() => callApi('/book/4')),
  queue.addPromise(() => callApi('/book/5')),
  queue.addPromise(() => callApi('/book/6')),
])
  .then(results => {
    // do something with the results
    return results
  })
```

There are scenarios when this approach doesn't work.

1) If I run 1000 promises and each returns a 10Mb API response, this needs 10GB memory.
2) I may decide to "feed" the promise endlessly with some kind of generator pattern. Then there is no simple way I could actually process results in the original order.

If I attach `then` handlers to the promises returned by `addPromise`, they are executed as soon as the inner requests complete:

```ts
import { ConcurrentPromiseQueue } from "concurrent-promise-queue"

const q = new ConcurrentPromiseQueue({ maxNumberOfConcurrentPromises: 5 })

async function fetchRemoteData(id: number) {
  await new Promise(resolve => setTimeout(resolve, Math.random() * 1000))
  return id
}

const input = Array.from({ length: 10 }).map((_, i) => i + 1) // 1...10

await Promise.all(input.map(id =>
  q.addPromise(() => fetchRemoteData(id)).then(data => console.log(data)),
))
```

prints:

```
1
2
5
7
8
9
6
3
4
10
```

What I propose is to have a flag to resolve the promises returned by `addPromise` in their original order. In the scenario above, I would do something like:

```ts
const q = new ConcurrentPromiseQueue({ maxNumberOfConcurrentPromises: 5, resolveInOrder: true })
```

and the *returned* promises will resolve from 1 to 10 while retaining the parallelism and throttling for the inner promises executors.

**Comment by doo-gl** [comment]
Published version v1.1.0 which adds the resolve in order behaviour described, closing this as a result.
